"
newForIcon: aModelClass
	^(self new)
		
	

"
Class {
	#name : #JSTreeTypeIcon,
	#superclass : #GRObject,
	#instVars : [
		'image',
		'position'
	],
	#category : #'JQWidgetBox-JSTree-Core'
}

{ #category : #accessing }
JSTreeTypeIcon >> image [
	^image
]

{ #category : #accessing }
JSTreeTypeIcon >> image: anObject [
	image := anObject
]

{ #category : #accessing }
JSTreeTypeIcon >> position [
	^position
]

{ #category : #accessing }
JSTreeTypeIcon >> position: anObject [
	position := anObject
]
